### ISSUE TITLE
此项目开发完了吗？

### ISSUE THREAD

**Issue by zhaoran112** [HiWayne/luban#28]

**Comment by HiWayne** [comment]
该项目现在转为公司内部开发了，github上还没更新，ToC已经基本上可用了，并且增加了很多功能，后面可能会继续开源到github。

**Comment by zhaoran112** [comment]
什么时候开源？



在 2023-04-21 16:12:10，"天宇" ***@***.***> 写道：

该项目现在转为公司内部开发了，github上还没更新，ToC已经基本上可用了，并且增加了很多功能，后面可能会继续开源到github。
